version: '3.9'

services:
  web:
    build: .
    ports:
      - '8000:8000'
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      # - "POSTGRES_HOST_AUTH_METHOD=trust"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    expose:
      - 5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: ppgadmin4_container
    restart: always
    ports: 
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ferreret@gmail.com
      PGADMIN_DEFAULT_PASSWORD: nina1974
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin-data:
